sudo: True
language: python
os:
  - linux
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then $ apt-get update; fi
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then $ apt-get install libunwind8; fi
install:
  - pip install codecov
  - pip install tox-travis
script:
  - tox
after_success:
  - codecov --token=d071f49d-847e-4de1-ae11-6a10e8b8aee0
